[package]
name = "raytracing-util"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
glam = "0.24.2"
vulkano = "0.35.1"
vulkano-util = "0.35.0"
