[package]
name = "weekend-shader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["lib", "dylib"]

[dependencies]
spirv-std = "0.9"
bytemuck = { version = "1.7.2", features = ["derive"] }
